<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>strapibackup-service</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Systemd" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\StrapiBackup.Sidecar\StrapiBackup.Sidecar.csproj" />
  </ItemGroup>
</Project>
